### PR TITLE
Update auth to check for access_token

### PR DESCRIPTION
**Pull request by pcj**

### CODE REVIEW

**Comment by pcj** [comment]
I signed it!

**Comment by pcj** [comment]
Fixes https://github.com/bazelbuild/rules_k8s/issues/128

**Comment by jonjohnsonjr** [comment]
Oops you beat me to it. Closing this in favor of #77 since it's a bit easier to sync internal -> external.

Thanks!

**Comment by pcj** [comment]
No problem!  I wasn't sure if you were prioritizing the go-containerregistry fix first so I thought I'd push it.

**Comment by jonjohnsonjr** [comment]
That project is still a bit of a WIP, but feel free to send PRs :)

It uses GitHub as the source of truth, so we can avoid the upstream juggling that we have to do for this project.

**Pull request closed without merging**
