### PR TITLE
Improve Python 3 compatibility

### PR DESCRIPTION
**Pull request by hwright**
This makes it possible for users with python 3 in Bazel to use these tools, either directly or transitively through `rules_docker`

### CODE REVIEW

**Comment by hwright** [comment]
Run ci

**Comment by hwright** [comment]
It would be nice if somebody could trigger CI again.  It looks like the Travis error is a timeout, which really isn't a failure mode I'd expect from this PR.

**Comment by mattmoor** [comment]
@hwright Travis doesn't provide secrets to PRs coming from branches in forks.  I need to merge this into the mono-repo and re-export.  This is small, so hopefully I can knock it off later today.

**Comment by hwright** [comment]
@mattmoor That's understandable, but also unfortunate that this repo can't accept external contributions easily.

Thanks for taking a look.

**Comment by hwright** [comment]
Also, it'd be useful to cut a release after this PR, so that `rules_docker` can use it.  For my specific use cases, this is the only instance where I could find python 3 incompatibilities.

**Comment by mattmoor** [comment]
Yeah I agree it is unfortunate, but the reason is that I want to have my cake and eat it too. :)

I want this library annotated with pytype annotations, but I also want it to be usable with unmodified python2.7 interpreters.  What's released here is a stripped version of the sources, which is why it has assorted oddities.

I have debated removing the annotations and/or switching to `.pyi`, but I'm not really happy with any of those situations (and the Travis bit would mean I still couldn't accept PRs easily).

**Comment by mattmoor** [comment]
See: https://github.com/google/containerregistry/pull/41

thanks for the PR!

**Pull request closed without merging**
