### PR TITLE
Small changes to auth flow and image push to support Amazon ECR

### PR DESCRIPTION
**Pull request by jmillikin-stripe**

### CODE REVIEW

**Comment by mattmoor** [comment]
Thanks for the PR.  We're currently generating this version from an internal copy.  I will incorporate this there and try to get it into a publicly exported release ASAP.

With this, were you able to get things working with ECR?

**Comment by jmillikin-stripe** [comment]
Yep! The image tarball (generated from a `docker_build()`) was pushed successfully. We're not using `docker_push()` for this because the repo name is too dynamic, but I bet it would work also.

I may have a few more small PRs to send in the future -- the push was a bit slow due to running gzip/sha256 on each layer, so it'd be nice to have some optimized format that `docker_build` could generate with all that preprocessing done at build time.

**Comment by mattmoor** [comment]
@jmillikin-stripe I am basically rewriting the intermediate form `docker_*` uses to achieve better performance, you can see the [open PRs](https://github.com/bazelbuild/rules_docker/pull/71) on that repo (they should be in a good state, if you feel like kicking the tires).
 
re: dynamic naming, have you seen the stamping support on `docker_push` and `docker_bundle`?  The K8s folks make use of this to dynamically tag things.  You can also use Makefile style variables e.g. `$(foo)` and pass `--define foo=bar` to Bazel (AFAIK, there is no good story for defaults here).

thanks again for the PR, you taught me something today (ECR uses `Basic` auth). :)

**Comment by jmillikin-stripe** [comment]
Well, using Bazel at all is kind of tricky for pushing -- we have separate systems for "build image" and "deploy image", and don't want to allow code in `BUILD` files to decide which repository the images get pushed to. Bazel's got a lot of auto-configuration magic that makes such rules difficult to enforce.

Thanks for the link to the "fast push" PR, I'll take a look and see if I have anything useful to contribute there.

**Comment by mattmoor** [comment]
@jmillikin-stripe Totally understand, this is generally a development fast-path internally, we typically generate `:foo.tar` and use a secure publishing process ourselves.

**Comment by mattmoor** [comment]
I tweaked things a bit, added it to v2 as well and added tests (internally).  Can you try out [this](https://github.com/google/containerregistry/pull/9) and LMK if it doesn't WAI?

thanks again for the PR, and LMK if there's anything we can do to improve things (here or `docker_*`).

**Pull request closed without merging**
